title: Anders Norås
description: The wonderful andersnoras.com website
sitename: andersnoras.com
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
  - external_resources
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME